Repository CS2103JAN2018-F12-B2/main, pull requests merged in 2018-04, with the labels that each got.

#47 Calories calculator
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/events/ui/ShowCaloriesEvent.java
  src/main/java/seedu/address/logic/commands/CaloriesCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CaloriesCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CaloriesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CaloriesCommandParserTest.java
Labels: type.documentation, type.enhancement, type.epic

#49 Updated user guide
  docs/UserGuide.adoc
  docs/images/Capture.PNG
Labels: type.documentation

#51 CApture.png didnt work
  docs/UserGuide.adoc
Labels: type.documentation

#54 Updated UserGuide to fix display inconsistencies
  docs/UserGuide.adoc
Labels: type.documentation

#57 Updated User Interface and README.adoc
  README.adoc
  docs/images/Ui.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/personal_trainer_pro_32.png
  src/main/resources/view/MainWindow.fxml
Labels: type.documentation

#56 v1.4 Major Enhancement
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/GoogleCalendar/AddEventManager.java
  src/main/java/seedu/address/GoogleCalendar/GoogleCalendarApi.java
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/GoogleCalendar/AddCalendarEvent.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/CalendarCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/CalendarEvent/CalendarEvent.java
  src/main/java/seedu/address/model/CalendarEvent/EventEndDate.java
  src/main/java/seedu/address/model/CalendarEvent/EventEndTime.java
  src/main/java/seedu/address/model/CalendarEvent/EventName.java
  src/main/java/seedu/address/model/CalendarEvent/EventStartDate.java
  src/main/java/seedu/address/model/CalendarEvent/EventStartTime.java
  src/main/java/seedu/address/model/ReadOnlyCalendarEvent.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/client_secret.json
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/model/CalendarEvent/EventDateTest.java
  src/test/java/seedu/address/model/CalendarEvent/EventNameTest.java
  src/test/java/seedu/address/model/CalendarEvent/EventTimeTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
Labels: help wanted, type.documentation, type.enhancement, type.epic

#87 New collateandcalorieschanges
  collated/functional/hypertun.md
  collated/test/hypertun.md
  src/main/java/seedu/address/commons/events/ui/ShowCaloriesEvent.java
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CaloriesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CaloriesCommandParserTest.java
  src/test/java/seedu/address/model/person/AgeTest.java
  src/test/java/seedu/address/model/person/GenderTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
Labels: type.documentation

#88 Changed all to lowercase
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/ui/BrowserPanel.java
Labels: issue.solved

#97 Added timeRestriction method
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/model/CalendarEvent/EventEndTime.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
Labels: type.enhancement

#98 Added activity level attribute
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/ActivityLevel.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/ActivityLevelTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.enhancement, type.epic

#100 Update user and developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/addEventCommand.PNG
  docs/images/calendarCommand.PNG
Labels: type.documentation

#101 Fixed Issue
  src/main/java/seedu/address/ui/MainWindow.java
Labels: issue.solved

#102 Minor issues
  .gitignore
  config.json
  docs/UserGuide.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/address/commons/core/Config.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: issue.solved

#104 Updated Developer Guide and User Guide
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.documentation

#106 Update UserGuide and DeveloperGuide
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ClassificationCommand.java
Labels: type.documentation

#107 Collation + Update theme of application to light theme
  src/main/java/seedu/address/GoogleCalendar/AddEventManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/default.html
Labels: type.enhancement

#108 Collatedeveryonev1.5
  collated/functional/hypertun.md
  collated/functional/wayneong95-reused.md
  collated/functional/wayneong95.md
  collated/functional/wenhao53.md
  collated/test/hypertun.md
  collated/test/wayneong95.md
  collated/test/wenhao53.md
Labels: type.documentation

#110 Created personal portfolio page
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/Ong Wei Sheng.adoc
Labels: type.documentation

#113 V1.5 Massive update
  README.adoc
  collated/functional/hypertun-reused.md
  collated/functional/hypertun.md
  docs/DeveloperGuide.adoc
  docs/team/Yeo Chong Han.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/address/model/util/HtmlFormatter.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonCard.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: type.epic

#115 Updated PPP, UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/Cheng Wenhao.adoc
Labels: type.documentation

#118 Updated user guide and ppp
  docs/UserGuide.adoc
  docs/team/Ong Wei Sheng.adoc
Labels: type.documentation

#119 Update user guide
  docs/UserGuide.adoc
Labels: type.documentation

#120 Update developer guide for manual testing and PPP
  docs/DeveloperGuide.adoc
  docs/team/Ong Wei Sheng.adoc
Labels: type.documentation

#122 Instruction Manual
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/Yeo Chong Han.adoc
Labels: type.documentation

#129 Updated Ivan's name
  docs/AboutUs.adoc
Labels: type.documentation

#130 Updated portfolio links and app title in UGDG
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/Cheng Wenhao.adoc
  docs/team/Ong Wei Sheng.adoc
Labels: type.documentation
