Repository CS2103JAN2018-F12-B2/main, pull requests merged in 2018-03, with the labels that each got.

#22 v1.1 Gender
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/GenderTest.java
  src/test/java/seedu/address/model/person/WeightTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: enhancement

#27 Added Height attribute and added relevant tests
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Height.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Weight.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/HeightTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.enhancement

#28 Age attribute added with preliminary panel adjustment
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/AgeTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: enhancement

#32 added developer guide to gender attribute
  docs/DeveloperGuide.adoc
Labels: documentation

#44 Updated User guide and developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.documentation
